# Shared agent metadata and installation behavior for Maslow-managed entry points.

omarchy_agent_resolve() {
  OMARCHY_AGENT_SYSTEM_PACKAGE=""
  case "${1:-}" in
  pi) OMARCHY_AGENT_ID="pi"; OMARCHY_AGENT_NAME="Pi"; OMARCHY_AGENT_PACKAGE="pi" ;;
  omp | oh-my-pi) OMARCHY_AGENT_ID="omp"; OMARCHY_AGENT_NAME="Oh My Pi"; OMARCHY_AGENT_PACKAGE="github:can1357/oh-my-pi" ;;
  opencode | open-code) OMARCHY_AGENT_ID="opencode"; OMARCHY_AGENT_NAME="OpenCode"; OMARCHY_AGENT_PACKAGE="opencode" ;;
  ori | openrouter) OMARCHY_AGENT_ID="ori"; OMARCHY_AGENT_NAME="Ori"; OMARCHY_AGENT_PACKAGE="github:OpenRouterLabs/ori-releases" ;;
  claude | claude-code) OMARCHY_AGENT_ID="claude"; OMARCHY_AGENT_NAME="Claude Code"; OMARCHY_AGENT_PACKAGE="claude" ;;
  codex) OMARCHY_AGENT_ID="codex"; OMARCHY_AGENT_NAME="Codex"; OMARCHY_AGENT_PACKAGE="codex" ;;
  crush) OMARCHY_AGENT_ID="crush"; OMARCHY_AGENT_NAME="Crush"; OMARCHY_AGENT_PACKAGE="crush" ;;
  grok) OMARCHY_AGENT_ID="grok"; OMARCHY_AGENT_NAME="Grok"; OMARCHY_AGENT_PACKAGE="npm:@xai-official/grok" ;;
  agy | antigravity | antigravity-cli | gemini | gemini-cli) OMARCHY_AGENT_ID="agy"; OMARCHY_AGENT_NAME="Antigravity"; OMARCHY_AGENT_PACKAGE="antigravity-cli" ;;
  hermes) OMARCHY_AGENT_ID="hermes"; OMARCHY_AGENT_NAME="Hermes"; OMARCHY_AGENT_PACKAGE="hermes" ;;
  copilot | github-copilot) OMARCHY_AGENT_ID="copilot"; OMARCHY_AGENT_NAME="GitHub Copilot"; OMARCHY_AGENT_PACKAGE="copilot" ;;
  *) return 1 ;;
  esac
  case "$OMARCHY_AGENT_ID" in
  codex) OMARCHY_AGENT_SYSTEM_PACKAGE="openai-codex-bin" ;;
  claude) OMARCHY_AGENT_SYSTEM_PACKAGE="claude-code" ;;
  hermes) OMARCHY_AGENT_SYSTEM_PACKAGE="hermes-agent" ;;
  esac
}

omarchy_agent_package_path() {
  printf '/usr/bin/%s' "$OMARCHY_AGENT_ID"
}

omarchy_agent_is_packaged() {
  [[ -n $OMARCHY_AGENT_SYSTEM_PACKAGE ]] &&
    omarchy-pkg-present "$OMARCHY_AGENT_SYSTEM_PACKAGE" &&
    [[ -f $(omarchy_agent_package_path) && -x $(omarchy_agent_package_path) ]]
}

omarchy_agent_package_on_path() {
  local resolved
  resolved=$(type -P "$OMARCHY_AGENT_ID") || return 1
  [[ $resolved -ef $(omarchy_agent_package_path) ]]
}

# Fresh users use the packaged binary directly. On re-finalization, retire only
# the exact lazy wrapper generated by omarchy-mise-install; never custom files.
omarchy_agent_prepare_packaged() {
  local wrapper backup_dir
  omarchy_agent_resolve "$1" || return 1
  if ! omarchy_agent_is_packaged; then
    echo "$OMARCHY_AGENT_NAME package is unavailable; no download-on-launch wrapper was created." >&2
    return 1
  fi
  wrapper="$HOME/.local/bin/$OMARCHY_AGENT_ID"
  if [[ ! -e $wrapper && ! -L $wrapper ]]; then
    return 0
  fi
  # Hermes has a different legacy installer and may be desktop-owned. Preserve
  # those launchers for explicit review instead of guessing their ownership.
  if [[ $OMARCHY_AGENT_ID != "hermes" && -f $wrapper && ! -L $wrapper ]] && cmp -s "$wrapper" <(printf '%s\n' \
    '#!/bin/bash' \
    'export MISE_MINIMUM_RELEASE_AGE=0' \
    "mise use -g --quiet \"$OMARCHY_AGENT_PACKAGE\" || exit 1" \
    "exec mise x \"$OMARCHY_AGENT_PACKAGE\" -- \"$OMARCHY_AGENT_ID\" \"\$@\""); then
    backup_dir="$HOME/.local/state/maslow-os/agent-wrapper-backups"
    mkdir -p "$backup_dir" || return 1
    chmod 0700 "$backup_dir" || return 1
    backup_dir=$(mktemp -d "$backup_dir/$OMARCHY_AGENT_ID.XXXXXX") || return 1
    mv -- "$wrapper" "$backup_dir/$OMARCHY_AGENT_ID" || return 1
    echo "Saved the old $OMARCHY_AGENT_NAME download wrapper to $backup_dir/$OMARCHY_AGENT_ID; the packaged command is now available."
  else
    echo "Preserved $wrapper; this user command may override the packaged $OMARCHY_AGENT_NAME." >&2
  fi
}

omarchy_agent_launch_mode() {
  case "$1" in
  opencode) printf '%s' "opencode:--auto" ;;
  agy) printf '%s' "agy:--dangerously-skip-permissions" ;;
  copilot) printf '%s' "copilot:--allow-all" ;;
  crush) printf '%s' "crush:--yolo" ;;
  claude) printf '%s' "claude:--permission-mode=auto" ;;
  grok) printf '%s' "grok:--permission-mode=bypassPermissions" ;;
  codex) printf '%s' "codex:--approve-for-me" ;;
  hermes) printf '%s' "hermes:--yolo" ;;
  omp) printf '%s' "omp:--auto-approve" ;;
  ori) printf '%s' "ori:code" ;;
  pi) printf '%s' "pi:interactive" ;;
  *) return 1 ;;
  esac
}

omarchy_agent_is_installed() {
  if omarchy_agent_is_packaged; then
    # Bare command launches must reach the same binary we checked. Preserve
    # user overrides, but never report them as verified packaged readiness.
    omarchy_agent_package_on_path
  elif [[ $OMARCHY_AGENT_ID == "hermes" ]]; then
    omarchy-install-hermes-cli --check
  else
    mise where "$OMARCHY_AGENT_PACKAGE" &>/dev/null
  fi
}

omarchy_agent_install_only() {
  if omarchy_agent_is_packaged; then
    if omarchy_agent_package_on_path; then
      return 0
    else
      echo "$OMARCHY_AGENT_NAME is packaged, but another command shadows it on PATH. Resolve the override before continuing." >&2
      return 1
    fi
  elif [[ $OMARCHY_AGENT_ID == "hermes" ]]; then
    omarchy-install-hermes-cli --now
  else
    mise use -g "$OMARCHY_AGENT_PACKAGE"
  fi
}
